### ISSUE TITLE
The add-ons do not work on the bot

### ISSUE THREAD

**Issue by theodelhay** [asanrom/Showdown-ChatBot#1]
Hello, I try to add something for the autovoice bot but it does not do anything, I try with other programs but no answer what to do?

**Comment by asanrom** [comment]
If you are trying this auto-voice add-on (https://github.com/asanrom/Showdown-ChatBot/wiki/Add-on:-Automated-promotion-to-voice), it works for me.

I don't know exactly what it happening in your case. But maybe it's one of the following:

 - Your bot may not be able to promote to voice. If your bot account has not enougth rank to promote, it cannot do it. make sure it is a moderator or above.
 - Maybe you misstyped the room ID. It cannot contain uppercase letters or non-alphanumeric characters (except '-'). I recommend you to invite the bot to the room to see the Room ID. For example, if I have a room called "Free Room, Join to get Voice!", the configuration it's the following:
```js
const Rooms = ['freeroomjointogetvoice'];
```
 - You cannot promote to voice in a room with no room owners. When you use the /roomvoice command it gives you the error message "/roompromote - This room isn't designed for per-room moderation".
 - If the user is already voice, it cannot be promoted to voice.
 - If the user account is not registered, it cannot be promoted to voice.

**Comment by asanrom** [comment]
Since no response, I am supposing you solved the problem, so I am closing this. Feel free to comment if you have any other issues.
